// <auto-generated />
namespace TravelApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SecMigration24122016 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SecMigration24122016));
        
        string IMigrationMetadata.Id
        {
            get { return "201612241552457_SecMigration24.12.2016"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
